language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  CODECLIMATE_REPO_TOKEN: dd47f2de1879cb2e4cbffe5310d925da9a088fd7a76c1e6443075659412b5dba
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: 
  POSTGRESQL_HOST: localhost
  global:
  - PGPORT=5432
services:
- postgresql

before_install:
  - openssl aes-256-cbc -K $encrypted_6d737e3f8fdd_key -iv $encrypted_6d737e3f8fdd_iv
    -in custom.json.enc -out data/storage/custom/custom.json -d

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- psql -c 'create database postput;' -U postgres
- npm install
- ./cc-test-reporter before-build

script:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- istanbul cover _mocha -- -R spec ./test/*.js
- codeclimate < ./coverage/lcov.info

