version: '3.3'

services:
  postput_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SEQUELIZE_FORCE_SYNC: "true"
    ports:
      - '2000:3000'
