apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: registry.gitlab.com/postput/api
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: api
        namespace: postput
        chartPath: charts/api
        #wait: true
        #recreatePods: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        setValues:
          image.pullSecrets[0].name: gitlab
        values:
          imageOverride: registry.gitlab.com/postput/api
